# Generated by Django 5.1.7 on 2025-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_uploaded_at_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
