version: 1
services:
  - type: web
    name: one-windows-app  # Уникальное имя вашего приложения
    env: python
    plan: free
    runtime: python-3.9    # Укажите версию Python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nwnd.wsgi:application --log-file -"
